baseURL = 'https://pivtorak.studio/'
defaultContentLanguage = 'uk'
title = 'Pivtorak.Studio'
theme = 'hugo-book'

[languages]
  [languages.uk]
    languageName = 'UA'
    contentDir = 'content/uk'
    weight = 1
  [languages.en]
    languageName = 'EN'
    contentDir = 'content/en'
    weight = 2
  [languages.pt]
    languageName = 'PT'
    contentDir = 'content/pt'
    weight = 3
  [languages.ru]
    languageName = 'RU'
    contentDir = 'content/ru'
    weight = 4

[params]
  BookLogo = 'logo.png'
  author = 'Anna Pivtorak'
  description = 'Digital Archive & Research Hub'
  BookSectionEnumerable = true
  # Вмикає перемикач мов
  BookTranslate = true
