backend:
  name: github
  repo: pivtorak-studio/pivtorak-studio.github.io
  branch: main # або master
base_url: https://api.netlify.com # Це важливо для Netlify

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "shield_ua"
    label: "Щит Нації (UA)"
    folder: "content/uk/docs/shield-of-nation"
    create: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Вага (порядок)", name: "weight", widget: "number", default: 10}
      - {label: "Текст статті", name: "body", widget: "markdown"}
